name: CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Ruff lint
        run: |
          ruff check .
          ruff format --check .

      - name: Run tests
        run: |
          pytest -q

