name: Lint

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install .[dev]

      - name: Ruff lint
        run: ruff check .

      - name: Ruff format
        run: ruff format --check .

