name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      target:
        description: "Publish target"
        required: true
        type: choice
        options:
          - pypi
          - testpypi

jobs:
  build-and-publish-pypi:
    name: Publish to PyPI
    if: >-
      (github.event_name == 'release' && github.event.release.prerelease == false) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'pypi')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/letta-evals
    permissions:
      id-token: write  # for trusted publishing
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check distribution metadata
      run: twine check dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  build-and-publish-testpypi:
    name: Publish to TestPyPI (pre-releases)
    if: >-
      (github.event_name == 'release' && github.event.release.prerelease == true) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'testpypi')
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/letta-evals
    permissions:
      id-token: write  # for trusted publishing
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check distribution metadata
      run: twine check dist/*

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
